//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCfdiConceptos
    {
        public int soptype { get; set; }
        public string sopnumbe { get; set; }
        public int lnitmseq { get; set; }
        public string itemnmbr { get; set; }
        public int cmpntseq { get; set; }
        public decimal facturadetalle_cantidadreal { get; set; }
        public string facturadetalle_cantidadrealunidadmedida { get; set; }
        public decimal facturadetalle_cantidadunidades { get; set; }
        public string cargosdescuentos_codigo { get; set; }
        public string cargosdescuentos_descripcion { get; set; }
        public int cargosdescuentos_indicador { get; set; }
        public int cargosdescuentos_monto { get; set; }
        public int cargosdescuentos_montobase { get; set; }
        public int cargodescuentos_porcentaje { get; set; }
        public string cargosdescuentos_secuencia { get; set; }
        public string facturadetalle_codigoproducto { get; set; }
        public string facturadetalle_descripcion { get; set; }
        public string facturadetalle_estandarcodigo { get; set; }
        public string facturadetalle_estandarcodigoproducto { get; set; }
        public string facturadetalle_marca { get; set; }
        public string facturadetalle_modelo { get; set; }
        public decimal facturadetalle_precioTotal { get; set; }
        public decimal facturadetalle_precioTotalSinImpuestos { get; set; }
        public decimal facturadetalle_precioVentaUnitario { get; set; }
        public string facturadetalle_secuencia { get; set; }
        public string facturadetalle_unidadMedida { get; set; }
    }
}
