//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCfdiRelacionados
    {
        public int orden { get; set; }
        public string tipoDocumento { get; set; }
        public Nullable<short> soptypeFrom { get; set; }
        public string sopnumbeFrom { get; set; }
        public int soptypeTo { get; set; }
        public string sopnumbeTo { get; set; }
        public string codigoInterno { get; set; }
        public string cufeDocReferenciado { get; set; }
        public string cufeDescripcion { get; set; }
        public string fecha { get; set; }
        public string numeroDocumento { get; set; }
        public string tipoCufe { get; set; }
    }
}
