//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCfdiFacturaImpuestosCabecera
    {
        public int soptype { get; set; }
        public string sopnumbe { get; set; }
        public decimal baseimponibletotalimp { get; set; }
        public string codigoTotalImp { get; set; }
        public string controlInterno { get; set; }
        public decimal porcentajeTotalImp { get; set; }
        public string unidadMedida { get; set; }
        public string unidadMedidaTributo { get; set; }
        public decimal valorTotalImp { get; set; }
        public string valorTributoUnidad { get; set; }
    }
}
