//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCfdiMediosDePago
    {
        public int soptype { get; set; }
        public string sopnumbe { get; set; }
        public string mediopago { get; set; }
        public string metodopago { get; set; }
        public string numeroreferencia { get; set; }
    }
}
